---
#global settings
my_server_id: 100
replica_batch_size: 1000
batch_retention: '1 day'
copy_max_memory: 300M
my_database: test
pg_database: test
source_name: 'default'
dest_schema: 'public'
copy_mode: 'file'
out_dir: /tmp

sleep_loop: 5

#Pause the replica for the given amount of seconds if a reindex process is found
pause_on_reindex: Yes
sleep_on_reindex: 30

#mysql connection's charset.
my_charset: 'utf8'
pg_charset: 'utf8'
reindex_app_names:
    - 'reindexdb'
    - 'my_custom_reindex'

hexify:
    - 'blob'
    - 'tinyblob'
    - 'mediumblob'
    - 'longblob'
    - 'binary'
    - 'varbinary'
    - 'geometry'

pid_dir: '~/.pg_chameleon/pid/'

log_dir: '~/.pg_chameleon/logs/'
log_level: 'debug'
log_dest: 'stdout'
log_days_keep: 10

#include tables only if empty = all table
tables_limit: ['de_store','shift_seq']

#mysql slave setup
mysql_conn:
    host: *****
    port: 3306
    user: root
    passwd: ***

#postgres connection
pg_conn:
    host: ***
    port: 5432
    user: postgres
    password: *****
